#!/bin/bash
echo compiling keygen.c
clang -o keygen keygen.c

echo compiling otp_enc.c
clang -o otp_enc otp_enc.c

echo compiling otp_enc_d.c
clang -o otp_enc_d otp_enc_d.c

echo compiling otp_dec_d.c
clang -o otp_dec_d otp_dec_d.c

echo compiling otp_dec.c
clang -o otp_dec otp_dec.c
